sudo: required
dist: trusty
language: node_js
node_js:
  - 12
python:
  - 3.5
cache:
  - pip
install:
  - pip install --user awscli
env:
  - TEST_DIR=./
script: cd $TEST_DIR && yarn --ignore-engines && npm test
deploy:
  provider: s3
  access_key_id: AKIAJXZLIYOY2NQ6EEDA
  secret_access_key:
    secure: TC+zMQs+P4GAAcjRGtdoPkZORcSVFPmSUbZO+DEZ1OzOhh6RuXVDVoPxJoVuAJyd996OkREQJkZ1DyfDvR0LKWLnxuIgg+wRkWzUVjZTbhBKWbimkobYbdjiE9+vZnK5q53YazMoGEOGgeGB6q27lQjOZizSc9duGet0QHv0/DxWHJcBnetqU82H5zyaxh6fp9vr30b5k7ZRzYAlzHMeowrFBhxl/0KZQ93IDQevvXe8DIR3BF+Wagcs+DdzizKPCLqFpd0CoyZ6vu6FOHh2YlKExsT4QCPGiUUGEZoFf+vuNjLeAGHVZnVYr4V7jAmqzCDqVaVnjcehledUNt42aYdrudTLPtBfxtGUdvp1+Gr7BWKjVIvF5/FrAQIh8M6yFJaC8vOgMpM8p1K2XyvXMpD0EL22VFvdnJ02hSW5eqXdL1BZIsMVVOSAmJXYleQHfFRyAUR8ADh29zEQVhXjQ0V6AQlTXJvaY2/JN9pLL0DiVRN2tOsu1CBBJ4BAQ3MDr19YxD2uiTd+4I3fTcXRBNYl34tp4shCTw5Y4HcgydtA+1lEbPqtPJNsGlIW3fmdqpd5fc33VcQBIQN4hvyX82Mgz5dBrBpNgDJQ3aCytdhNaP7w8I0XIdfSTlvF9bO5PdvdrQkOFcR3wF2ZwI7gjE//Ue6ckE+FIa0dXMQw2wo=
  bucket: omnitag.omniscientai.com
  region: ap-northeast-1
  acl: public_read
  cache_control: "max-age=600"
  on:
    repo: omnitag/omnitag
after_deploy:
  - aws configure set aws_access_key_id AKIAJXZLIYOY2NQ6EEDA 
  - aws configure set aws_secret_access_key $AWS_SECRET_ID
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
