; Bebit

; Tags
tag_usergram_enabled=true
tag_usergram_id="UgVTMw-1"
tag_usergram_test=true

; Router
router_rules[]="/*"
router_pages[]='all'


; Page
page_all_scripts[]=initUserId
page_all_params[]=[]
page_all_secs[]='clickTest'

; Section
sec_clickTest_selects[]="button"
sec_clickTest_types[]="click"
sec_clickTest_scripts[]="clickButton"
sec_clickTest_params[]=[]


script_clickButton="
<script>
alert(JSON.stringify(window.usergram));
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = get(window, ['serviceId']);
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
