; Bebit

; Tags
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="UA-35157766-1"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_usergram_enabled=false
tag_usergram_id="UgVTMw-1"
tag_usergram_test=false
tag_usergram_cv[]=Contact
tag_usergram_cv[]=NPS
tag_usergram_attr_gender=prop01
tag_usergram_attr_city=prop03
tag_usergram_attr_category=prop04
tag_usergram_attr_department=prop05

; Router
router_rules[]="/*"
router_pages[]='all'
router_rules[]="/contact-us/*"
router_pages[]='contact'


; Page
page_all_secs[]="nps"
page_contact_secs[]="contact"


; Section
sec_contact_selects[]=".container form input[type=submit]"
sec_contact_types[]="click"
sec_contact_scripts[]="submitContact"
sec_contact_params[]=[]

sec_nps_selects[]="#nps-popup-modal form button"
sec_nps_types[]="delegate"
sec_nps_scripts[]="submitNps"
sec_nps_params[]=[]


; Script
script_submitContact="
<script>
var g = window.i13n;

g.dispatch('action', {
  I13N: {
    category: 'Contact',
    action: 'Contact'
  }
});
</script>
"

script_submitNps="
<script>
var g = window.i13n;

g.dispatch('action', {
  I13N: {
    category: 'Contact',
    action: 'NPS'
  }
});
</script>
"


script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = get(window, ['serviceId']);
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
