; User: cyberbiz https://www.kgcshop.com.tw/ 

; Tags
currencyCode=TWD
tagId=OA-c1af6551
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp

; Router
router_rules[]="/*"
router_pages[]='allInit'

router_rules[]="/"
router_pages[]='home'

router_rules[]="/*"
router_pages[]='all'

; Page
page_allInit_scripts[]=testScript
page_allInit_params[]=[]

page_home_scripts[]=home
page_home_params[]=[]

page_all_scripts[]=getUid
page_all_params[]=[]


; Script
script_testScript="
<script>
console.log('test cyberbiz');
</script>
"

script_home="
<script>
var g = window.i13n;
var query = g.query;
var hotProduct = query.all('.product-col');
var objectToArray = g.objectToArray;
var prods = {}; 
hotProduct.forEach(function(prod){
  var prodLink = query.from(prod).one('a.productClick');
  if (prodLink) {
    var name = prodLink.getAttribute("data-name");
    var id = prodLink.getAttribute("data-id");
    var price = prodLink.getAttribute("data-price");
    var brand = prodLink.getAttribute("data-brand");
    var category = prodLink.getAttribute("data-category");
    var list = prodLink.getAttribute("data-list");
    var position = prodLink.getAttribute("data-position");
    prods[id] = {
      id: id,
      price: price,
      brand: brand,
      category: category,
      list: list,
      position: position
    };
  }
});

g.dispatch({
  i13nPage: {
    impressions: objectToArray(prods),
  }
});

</script>
"

script_getUid="
<script>
var g = window.i13n;
var lStorage = g.lStorage;
var get = g.get;
var c = lStorage('customer')();
var uid = get(c, ['id']);
if (uid) {
  g.dispatch({ uid: uid });
}
</script>
"
