; User: cyberbiz https://www.kgcshop.com.tw/ 

; Tags
currencyCode=TWD
tagId=OA-19c95c3b
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp
tag_gtag_downstreams[]=official

; Router
router_rules[]="/*"
router_pages[]='allInit'

router_rules[]="/"
router_pages[]='home'

router_rules[]="/*"
router_pages[]='all'

; Page
page_allInit_scripts[]=allInit
page_allInit_params[]=[]

page_home_scripts[]=home
page_home_params[]=[]
page_home_secs[]=clickProduct
page_home_secs[]=addToCart

page_all_scripts[]=getUid
page_all_params[]=[]

; Section
sec_clickProduct_selects[]=".product-col a.productClick"
sec_clickProduct_types[]="click"
sec_clickProduct_scripts[]="clickProduct"
sec_clickProduct_params[]=[]

; Section
sec_addToCart_selects[]="div[id*='addcart-Modal-'] button"
sec_addToCart_types[]="click"
sec_addToCart_scripts[]="addToCart"
sec_addToCart_params[]=[]

; Script
script_allInit="
<script>
</script>
"

script_addToCart="
<script>
</script>
"

script_clickProduct="
<script>
</script>
"

script_home="
<script>
</script>
"

script_getUid="
<script>
</script>
"
