; User: June1 https://www.june1.com.tw/ 

; Tags
currencyCode=TWD
tagId=OA-19c95c3b
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="UA-127045625-5"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp
tag_gtag_downstreams[]=official

; Router
 
router_rules[]="/*"
router_pages[]='allInit'

router_rules[]="/"
router_pages[]="home"

router_rules[]="/website/product_list*"
router_pages[]="category"

router_rules[]="/website/product_detail*"
router_pages[]="detail"

router_rules[]="/website/cart/*"
router_pages[]="checkoutStep1"

router_rules[]="/website/cart_step02*"
router_pages[]="checkoutStep2"

router_rules[]="/website/cart_step03*"
router_pages[]="checkoutStep3"

router_rules[]="/website/cart_step04*"
router_pages[]="checkoutStep4"

router_rules[]="/*"
router_pages[]="all"

; Page

page_allInit_scripts[]=allInit
page_allInit_params[]=[]

page_checkoutStep4_scripts[]=checkoutStep4
page_checkoutStep4_params[]=[]

page_checkoutStep3_scripts[]=checkoutStep3
page_checkoutStep3_params[]=[]

page_checkoutStep2_scripts[]=checkoutStep2
page_checkoutStep2_params[]=[]
page_checkoutStep2_secs[]=clickCheckout

page_checkoutStep1_scripts[]=checkoutStep1
page_checkoutStep1_params[]=[]
page_checkoutStep1_secs[]=clickCheckout

page_home_scripts[]=home
page_home_params[]=[]

page_category_scripts[]=initCategory
page_category_params[]=[]
page_category_secs[]=clickProduct

page_detail_scripts[]=initDetail
page_detail_params[]=[]
; add To Cart handle on page

page_all_scripts[]=getUid
page_all_params[]=[]

; Section

sec_clickCheckout_selects[]="input[type="submit"]"
sec_clickCheckout_types[]="click"
sec_clickCheckout_scripts[]="clickCheckout"
sec_clickCheckout_params[]=[]

sec_clickProduct_selects[]=".products-list .gray-border-box a"
sec_clickProduct_types[]="click"
sec_clickProduct_scripts[]="clickProduct"
sec_clickProduct_params[]=[]


; Script

script_allInit="
<script>
</script>
"

script_checkoutStep4="
<script>
var g = window.i13n;
var query = g.query;
var text = g.text;
var keys = g.keys;
var getRandomId = g.getRandomId;
g.dispatch('action', {
  withLazy: 'Purchase',
  i13nCb: function(e, I13N) {
    if (!keys(I13N || {}).length) {
      return;
    }
    var idEl = query.one('.noticeInfo span span'); 
    var purchaseId = text(idEl) || getRandomId();
    I13N.purchaseId = purchaseId;
    return I13N;  
  }
});
</script>
"

script_checkoutStep3="
<script>
var g = window.i13n;
var query = g.query;
var getNum = g.getNum;
var text = g.text;
g.dispatch('action', {
  wait: 99,
  withLazy: 'Purchase',
  lazyKey: 'Purchase',
  i13nCb: function(e, I13N) {
    var revenue = getNum(query.one('.all-money-box'));
    var tryGetShipping = query.all('.e.col-2.col-s-12');
    var shipping;
    var coupon = 0;
    tryGetShipping.forEach(function(el){
      var txt = text(el);
      if (-1 !== txt.indexOf('運費')){
        shipping = getNum(el);
      } else if (-1 !== txt.indexOf('Coupon')) {
        coupon = getNum(el);
      }
    });
    I13N.revenue = revenue;
    I13N.shipping = shipping;
    I13N.coupon = coupon;
    return I13N;
  }
});
</script>
"

script_checkoutStep2="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
var getElValue = g.getElValue;
var products = gData.checkoutProducts;
g.dispatch('action', {
  I13N: {
    action: 'Checkout',
    stepNo: 3,
    label: {
      email: getElValue('input[name="orderemail"]'),
    },
    products: products
  }
});
g.dispatch('action', {
  wait: 99,
  stop: true,
  lazyKey: 'Purchase',
  I13N: {
    action: 'Purchase',
    products: products,
  }
});
</script>
"

script_clickCheckout="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
var products = gData.checkoutProducts || null;
g.dispatch('action', {
  wait: 0,
  I13N: {
    action: 'ClickCheckout',
    stepNo: 2,
    products: products
  }
});
</script>
"

script_checkoutStep1="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
var products = gData.checkoutProducts;
g.dispatch('action', {
  I13N: {
    action: 'Checkout',
    stepNo: 1,
    products: products
  }
});
</script>
"

script_initDetail="
<script>
var g = window.i13n;
var gData = window.i13nData || {};

g.dispatch({
  i13nPage: {
    detailProducts: [gData.detailProducts]
  }
});
</script>
"

script_clickProduct="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
var arrayToObject = g.arrayToObject;
var get = g.get;
var arrP = arrayToObject(gData.impressions, 'id');
g.dispatch('action', { 
  wait: 0,
  I13N: {
    action: 'ClickProduct',
  },
  i13nCb: function(e, I13N, p, state) {
    e.preventDefault();
    var t = e.currentTarget;
    var attr = t.getAttribute('onClick');
    var regResult = /(ClickProduct\(')([^']*)/.exec(attr); 
    var productId = regResult[2];
    var prod = get(arrP, [productId]);
    if (prod) {
      I13N.products = [prod];
      return I13N;
    }
  }
});
</script>
"

script_initCategory="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
g.dispatch({
  i13nPage: {
    p: 'category',
    impressions: gData.impressions,
  }
});
</script>
"

script_home="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
g.dispatch({
  i13nPage: {
    p: 'home',
    impressions: gData.impressions,
  }
});
</script>
"

script_getUid="
<script>
var g = window.i13n;
var gData = window.i13nData || {};
var u = gData.uid;
if (u != null) {
  g.dispatch({ uid: u });
}
</script>
"
