; https://muzuopet.com/
; type: waca

; Tags
currencyCode=TWD
tagId=OA-fdcc8bdd
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp

; Router
router_rules[]="/*"
router_pages[]='allInit'


router_rules[]="/product/all"
router_pages[]="category"
router_rules[]="/category/*"
router_pages[]="category"

; Page
page_allInit_scripts[]=testScript
page_allInit_params[]=[]
page_allInit_secs[]=testClick

page_category_scripts[]=initCategory
page_category_params[]=[]

; Section
sec_testClick_selects[]="#test-click"
sec_testClick_types[]="click"
sec_testClick_scripts[]="testClick"
sec_testClick_params[]=[]

; Script
script_testScript="
<script>
console.log('test');
</script>
"

script_initCategory="
<script>
console.log('test-category');
</script>
"
