; https://muzuopet.com/
; type: waca

; Tags
currencyCode=TWD
tagId=OA-fdcc8bdd
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="G-E7MR9XTXSV"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp
tag_gtag_downstreams[]=official

; Router
router_rules[]="/*"
router_pages[]='allInit'

router_rules[]="/cart/finish*"
router_pages[]="purchase"

router_rules[]="/cart"
router_pages[]="checkout"

router_rules[]="/product/detail/*"
router_pages[]="detail"

router_rules[]="/"
router_pages[]="category"
router_rules[]="/product/all"
router_pages[]="category"
router_rules[]="/category/*"
router_pages[]="category"

router_rules[]='/*'
router_pages[]='all'

; Page
page_allInit_scripts[]=initUserId
page_allInit_params[]=[]

page_all_secs[]=clickRemoveCart
page_all_secs[]=globalAddToCart

page_purchase_scripts[]=initPurchase
page_purchase_params[]=[]

page_checkout_scripts[]=initCheckout
page_checkout_params[]=[]

page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_secs[]=detailAddToCart

page_category_scripts[]=initCategory
page_category_params[]=[]
page_category_secs[]=clickProduct

; Section

sec_clickRemoveCart_selects[]=".js_cart_menu_del_item"
sec_clickRemoveCart_types[]="delegate"
sec_clickRemoveCart_scripts[]="clickRemoveCart"
sec_clickRemoveCart_params[]=[]
sec_clickRemoveCart_selects[]=".js_cart_list_del_item a"
sec_clickRemoveCart_types[]="delegate"
sec_clickRemoveCart_scripts[]="clickRemoveCart"
sec_clickRemoveCart_params[]=[]

sec_globalAddToCart_selects[]=".jconfirm-box-container .js_btn_addcart"
sec_globalAddToCart_types[]="delegate"
sec_globalAddToCart_scripts[]="globalAddToCart"
sec_globalAddToCart_params[]=["AddToCart"]
sec_globalAddToCart_selects[]=".jconfirm-box-container .js_add_and_go_cart"
sec_globalAddToCart_types[]="delegate"
sec_globalAddToCart_scripts[]="globalAddToCart"
sec_globalAddToCart_params[]=["BuyNow"]

sec_detailAddToCart_selects[]="button.js_add_cart"
sec_detailAddToCart_types[]="click"
sec_detailAddToCart_scripts[]="addToCart"
sec_detailAddToCart_params[]=["AddToCart"]
sec_detailAddToCart_selects[]="button.js_add_and_go_cart"
sec_detailAddToCart_types[]="click"
sec_detailAddToCart_scripts[]="addToCart"
sec_detailAddToCart_params[]=["BuyNow"]

sec_clickProduct_selects[]="#product-list [href*="/product/detail"]"
sec_clickProduct_types[]="click"
sec_clickProduct_scripts[]="clickProduct"
sec_clickProduct_params[]=[]

; Script

script_initPurchase="
<script>
var g = window.i13n;
var get = g.get;
var arraySearchFirst = g.arraySearchFirst;
var parseJson = g.parseJson;
var getDataLayer = function() {
  var dl = get(window, ['dataLayer'], []);
  var data = arraySearchFirst(dl, function(haystack, needle){
    if (haystack.ecommerce) {
      return true;
    }
  })(null, function(d){return d});
  return parseJson(JSON.stringify(get(data, ['ecommerce', 'purchase'])));
};
var purchaseData = getDataLayer();
if (purchaseData) {
  g.dispatch({
    i13nPage: {
      purchaseId: get(purchaseData, ["actionField", "id"]),
      revenue: get(purchaseData, ["actionField", "revenue"]),
      coupon: get(purchaseData, ["actionField", "coupon"]),
      affiliation: get(purchaseData, ["actionField", "affiliation"]),
      shipping: get(purchaseData, ["actionField", "shipping"]),
      products: get(purchaseData, ["products"]),
    }
  });
}
</script>
"

script_initCheckout="
<script>
var g = window.i13n;
var get = g.get;
var arraySearchFirst = g.arraySearchFirst;
var parseJson = g.parseJson;
var getDataLayer = function() {
  var dl = get(window, ['dataLayer'], []);
  var data = arraySearchFirst(dl, true)({event: "checkout"});
  return parseJson(JSON.stringify(get(data, ['ecommerce', 'checkout', 'products'])));
};
var products = getDataLayer();
if (products) {
  g.dispatch({
    i13nPage: {
      stepNo: 1,
      products: products
    }
  });
}
</script>
"

script_clickRemoveCart="
<script>
var g = window.i13n;
var get = g.get;
var arraySearchFirst = g.arraySearchFirst;
var parseJson = g.parseJson;
var query = g.query
var getDataLayer = function() {
  var dl = get(window, ['dataLayer'], []);
  dl = parseJson(JSON.stringify(dl)).reverse();
  var data = arraySearchFirst(dl, true)({event: "removeFromCart"});
  return data;
};
g.dispatch('action', {
  i13nCb: function(e, I13N) {
    setTimeout(function(){
      var data = getDataLayer();
      if (data) {
        g.dispatch('action', {
          I13N: {
            action: 'RemoveFromCart',
            products: get(data, ["ecommerce", "remove", "products"]), 
          }
        });
      }
    }, 1000);
    return false;
  }
});
</script>
"

script_globalAddToCart="
<script>
var g = window.i13n;
var get = g.get;
var arraySearchFirst = g.arraySearchFirst;
var parseJson = g.parseJson;
var query = g.query
var merge = g.merge;
var getElValue = g.getElValue;

var getDataLayer = function() {
  var dl = get(window, ['dataLayer'], []);
  dl = parseJson(JSON.stringify(dl)).reverse();
  var data = arraySearchFirst(dl, true)({event: "addToCart"});
  return data;
};

var regDlPush = function(props) {
  var dl = get(window, ['dataLayer'], []);
  var origPush= dl.push;
  dl.push = function(d) {
    if ("add_to_cart" === d[1]) {
      var products = [merge(
        get(d, [2, "items", 0]),
        {quantity: props.quantity},
      )];
      g.dispatch('action', {
        wait: 0,
        I13N: {
          action: props.action,
          products: products,
        }
      });
    }
    origPush(d);
    dl.push = origPush;
  };
}

g.dispatch('action', {
  i13nCb: function(e, I13N, p) {
    var quantity = getElValue('select.js_product_qty');
    if (p[0] !== "BuyNow") {
      setTimeout(function(){
        var data = getDataLayer();
        var products = [merge(
          get(data, ["ecommerce", "add", "products", 0]),
          {quantity: quantity},
        )];
        if (data) {
          g.dispatch('action', {
            I13N: {
              action: p[0],
              products: products,
            }
          });
        }
      }, 1000);
    } else {
      regDlPush({quantity: quantity, action: p[0]});
    }
    return false;
  }
});
</script>
"

script_addToCart="
<script>
var g = window.i13n;
var merge = g.merge;
var getElValue = g.getElValue;
g.dispatch('action', { 
  i13nCb: function(e, I13N, p) {
    var quantity = getElValue('input[name="quantity"]');
    I13N = {
      action: p[0],
      products: [merge(
        g.pInfo,
        {quantity: quantity}
      )],
    };
    if (p[0] !== "BuyNow") {
      return I13N;
    } else {
      g.dispatch('action', {wait: 0, I13N: I13N});
      return false;
    }
  },
});
</script>
"

script_initDetail="
<script>
var g = window.i13n;
var get = g.get;
var arraySearchFirst = g.arraySearchFirst;
var parseJson = g.parseJson;
var getDataLayer = function() {
  var dl = get(window, ['dataLayer'], []);
  var data = arraySearchFirst(dl, function(haystack, needle){
    if (haystack.ecommerce) {
      return true;
    }
  })(null, function(d){return d});
  return parseJson(JSON.stringify(get(data, ['ecommerce', 'detail', 'products', 0])));
};
var pInfo = getDataLayer();
g.pInfo = parseJson(JSON.stringify(pInfo));
g.dispatch({
  pInfo: pInfo, 
  i13nPage: {
    detailProducts: [pInfo]
  }
});
</script>
"

script_clickProduct="
<script>
var g = window.i13n;
g.dispatch('action', { 
  wait: 0,
  I13N: {
    action: 'ClickProduct'
  },
  i13nCb: function(e, I13N) {
    var t = e.currentTarget; 
    var pData = g.parseProduct(t.getAttribute("onClick"));
    I13N.products = [pData];
    return I13N;
  },
});
</script>
"

script_initCategory="
<script>
var g = window.i13n;
var query = g.query;
var parseJson = g.parseJson;
var get = g.get;
g.parseProduct = function(data) {
  if (data) {
    var a = data.split("dataLayer.push({") || [];
    if (a[1]) {
      var dataLayerData = eval('({'+a[1].substring(0, a[1].length - 1));
      var pData = get(dataLayerData, ["ecommerce", "click", "products", 0]); 
      return pData;
    }
  }
};
var getProducts = function() {
  var products = query.all('#product-list [href*="/product/detail"]');
  var arrProds = [];
  products.forEach(function(prod, index){
    var pData = g.parseProduct(prod.getAttribute("onclick"));
    if (pData) {
      pData.position = index;
      arrProds.push(pData);
    }
  });
  return arrProds;
};
var arrP = getProducts();
g.dispatch({
  i13nPage: {
    impressions: arrP,
  }
});
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = get(window, ['mem', 'external_id']);
if (u) {
}
var path = document.location.pathname;
if (0 === path.indexOf("/search/")) {
  var kw = get(path.split("/"), [2]);
  g.dispatch("action", {
    I13N: {
      action: "Search",
      label: {
        search_string: kw
      }
    }
  });
}
</script>
"
