; https://muzuopet.com/
; type: waca

; Tags
currencyCode=TWD
tagId=OA-fdcc8bdd
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="G-E7MR9XTXSV"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp
tag_gtag_downstreams[]=official

; Router
router_rules[]="/*"
router_pages[]='allInit'


router_rules[]="/product/all"
router_pages[]="category"
router_rules[]="/category/*"
router_pages[]="category"

; Page
page_allInit_scripts[]=initUserId
page_allInit_params[]=[]

page_category_scripts[]=initCategory
page_category_params[]=[]
page_category_secs[]=clickProduct

; Section
sec_clickProduct_selects[]="#product-list [href*="/product/detail"]"
sec_clickProduct_types[]="click"
sec_clickProduct_scripts[]="clickProduct"
sec_clickProduct_params[]=[]

; Script
script_clickProduct="
<script>
var g = window.i13n;
g.dispatch('action', { 
  wait: 0,
  I13N: {
    action: 'ClickProduct'
  },
  i13nCb: function(e, I13N) {
    var t = e.currentTarget; 
    var pData = g.parseProduct(t.getAttribute("onClick"));
    I13N.products = [pData];
    return I13N;
  },
});
</script>
"

script_initCategory="
<script>
var g = window.i13n;
var query = g.query;
var parseJson = g.parseJson;
var get = g.get;
g.parseProduct = function(data) {
  if (data) {
    var a = data.split("dataLayer.push({") || [];
    if (a[1]) {
      var dataLayerData = eval('({'+a[1].substring(0, a[1].length - 1));
      var pData = get(dataLayerData, ["ecommerce", "click", "products", 0]); 
      return pData;
    }
  }
};
var getProducts = function() {
  var products = query.all('#product-list [href*="/product/detail"]');
  var arrProds = [];
  products.forEach(function(prod, index){
    var pData = g.parseProduct(prod.getAttribute("onclick"));
    if (pData) {
      pData.position = index;
      arrProds.push(pData);
    }
  });
  return arrProds;
};
var arrP = getProducts();
g.dispatch({
  i13nPage: {
    impressions: arrP,
  }
});
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = get(window, ['mem', 'external_id']);
if (u) {
}
</script>
"
