; <!-- prettier-ignore-start -->
; <!-- prettier-ignore -->
; User: Petpetgo https://petpetgo.com/

; Tags 
currencyCode=TWD
tagId=OA-1597cbff
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="UA-127045625-3"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp
tag_gtag_downstreams[]=official

; Router
router_rules[]='/*'
router_pages[]='all'

router_rules[]='/sign*'
router_pages[]='officialMember'

router_rules[]='/users/sign_in*'
router_pages[]='shoppingMember'

router_rules[]="/"
router_pages[]="category"

router_rules[]="/category/*"
router_pages[]="category"

router_rules[]="/brand/*"
router_pages[]="category"

router_rules[]="/product/*"
router_pages[]="detail"

router_rules[]="/cart"
router_pages[]="checkout"

router_rules[]="/checkout"
router_pages[]="checkout2"

router_rules[]="/search*"
router_pages[]=search

router_rules[]='/checkout-success*'
router_pages[]='orders'

router_rules[]="/me/orderDetail*"
router_pages[]=memberOrder

; Page
page_all_scripts[]=initUserId
page_all_params[]=[]
page_all_secs[]=globalAddToCart
page_all_secs[]=clickProduct
page_all_timeout=500

page_officialMember_secs[]=officialMemberSignUp
page_shoppingMember_secs[]=shoppingMemberSignUp

page_checkout_scripts[]=checkoutLib
page_checkout_params[]=[]
page_checkout_scripts[]=initCheckout
page_checkout_params[]=[]
page_checkout_secs[]=clickRemoveCart
page_checkout_secs[]=clickConfirmCheckout

page_checkout2_scripts[]=checkoutLib
page_checkout2_params[]=[]
page_checkout2_scripts[]=initCheckout2
page_checkout2_params[]=[]

page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_secs[]=detailAddToCart

page_search_scripts[]=initSearch
page_search_params[]=[]

page_category_scripts[]=initCategory
page_category_params[]=[]

page_orders_scripts[]=purchase
page_orders_params[]=[]

page_memberOrder_secs[]=refund

; Section
sec_officialMemberSignUp_selects[]='.sign-up-form__submit button[type="submit"]'
sec_officialMemberSignUp_types[]=click
sec_officialMemberSignUp_scripts[]=officialMemberSignUp
sec_officialMemberSignUp_params[]=[]

sec_shoppingMemberSignUp_selects[]='form button[type="submit"]'
sec_shoppingMemberSignUp_types[]=delegate
sec_shoppingMemberSignUp_scripts[]=shoppingMemberSignUp
sec_shoppingMemberSignUp_params[]=[]

sec_shoppingMemberSignUp_selects[]='.oauth-btns .google-auth-btn'
sec_shoppingMemberSignUp_types[]=delegate
sec_shoppingMemberSignUp_scripts[]=shoppingMemberSignUp
sec_shoppingMemberSignUp_params[]=["google"]

sec_shoppingMemberSignUp_selects[]='.oauth-btns .facebook-auth-btn'
sec_shoppingMemberSignUp_types[]=delegate
sec_shoppingMemberSignUp_scripts[]=shoppingMemberSignUp
sec_shoppingMemberSignUp_params[]=["facebook"]

sec_clickRemoveCart_selects[]="button.confirm-dialog__confirm"
sec_clickRemoveCart_types[]="click"
sec_clickRemoveCart_scripts[]="clickRemoveCart"
sec_clickRemoveCart_params[]=[]

sec_globalAddToCart_selects[]=".banner-product-card__price-row span.icon-shoppingCart"
sec_globalAddToCart_types[]="click"
sec_globalAddToCart_scripts[]="globalAddToCart"
sec_globalAddToCart_params[]=["AddToCart"]

sec_detailAddToCart_selects[]=".add-to-cart__button-group__submit"
sec_detailAddToCart_types[]="click"
sec_detailAddToCart_scripts[]="addToCart"
sec_detailAddToCart_params[]=["AddToCart"]

sec_clickProduct_selects[]=".banner-product-card__image-container"
sec_clickProduct_types[]="click"
sec_clickProduct_scripts[]="clickProduct"
sec_clickProduct_params[]=[]

sec_clickConfirmCheckout_selects[]="button.action-checkout"
sec_clickConfirmCheckout_types[]="click"
sec_clickConfirmCheckout_scripts[]="clickConfirmCheckout"
sec_clickConfirmCheckout_params[]=[]

sec_refund_selects[]='.confirm-dialog__confirm'
sec_refund_types[]='click'
sec_refund_scripts[]='refund'
sec_refund_params[]=[]

; <!-- prettier-ignore-end -->

; Script

script_shoppingMemberSignUp="
<script>
  var g = window.i13n;
  var get = g.get;
  g.dispatch("action", {
    wait: 0,
    lazyKey: "CompleteRegistration",
    I13N: {
      action: "CompleteRegistration",
    },
    i13nCb: function (e, I13N, params) {
      I13N.label = { regType: get(params, [0]) };
      return I13N;
    },
  });
</script>
" 

script_officialMemberSignUp="
<script>
  var g = window.i13n;
  var get = g.get;
  var query = g.query;
  var getNum = g.getNum;
  var getElValue = g.getElValue;
  g.dispatch("action", {
    wait: 0,
    lazyKey: "CompleteRegistration",
    I13N: {
      action: "CompleteRegistration",
    },
    i13nCb: function (e, I13N) {
      var t = e.currentTarget;
      var signUpForm = query.ancestor(t, "form.sign-up-form");
      var contact = getElValue("#mobileOrEmailInput", signUpForm);
      if (!contact) {
        return false;
      }
      var isEmail = contact.includes("@");
      if (isEmail) {
        I13N.label = { email: contact };
      } else {
        I13N.label = { mobile: contact };
      }
      return I13N;
    },
  });
</script>
" 

script_checkoutLib="
<script>
  var g = window.i13n;
  var query = g.query;
  var text = g.text;
  var getNum = g.getNum;
  var getElValue = g.getElValue;
  var fbqInfo = query.all("script").find((item) => {
    var json = JSON.stringify(item.outerHTML);
    return json.includes("InitiateCheckout");
  });
  var productIdsList = [];
  var productNameList = [];
  var productBrandList = [];

  if (fbqInfo) {
    var fbqInfo = fbqInfo.innerHTML;
    var productIdStrSplit = fbqInfo
      .match(/content_ids:"[0-9,]*"/)[0]
      .split('"');
    var productNameStrSplit = fbqInfo
      .match(/content_name:"[\s\S,]*",content_category/)[0]
      .split('"');
    var productBrdStrSplit = fbqInfo
      .match(/product_brand:"[\s\S,]*",currency/)[0]
      .split('"');
    if (productIdStrSplit.length > 1) {
      productIdsList = productIdStrSplit[1].split(",");
      productNameList = productNameStrSplit[1].split(",");
      productBrandList = productBrdStrSplit[1].split(",");
    }
  }

  g.getCheckoutProducts = function () {
    var isInCart = location.pathname.includes("cart");
    var products = [];
    var pRows;
    if (isInCart) {
      pRows = query.all("div.cart-rows__box .cart-column.cart-column__product");
    } else {
      pRows = query.all(
        ".bp3-collapse-body div.collapse-row.order-detail__row"
      );
    }

    if (pRows && pRows.length) {
      pRows.forEach(function (row, index) {
        var quantity;
        var price;
        if (isInCart) {
          quantity = getNum(getElValue(".bp3-input-group input", row));
          price = getNum(row.querySelector("div.column-price"));
        } else {
          quantity = getNum(row.querySelector(".order-detail__amount"));
          price = getNum(row.querySelector("div.order-detail__price"));
        }
        if (quantity == null) {
          quantity = getNum(row.querySelector("input"));
        }

        products.push({
          name: productNameList[index],
          id: productIdsList[index],
          brand: productBrandList[index],
          price: price,
          quantity: quantity,
        });
      });
    }
    return products;
  };
</script>
"

script_initCheckout="
<script>
  var g = window.i13n;
  var products = g.getCheckoutProducts() || [];
  var get = g.get;
  var query = g.query;
  var delegate = g.delegate;

  if (products) {
    g.dispatch({
      i13nPage: {
        stepNo: 3,
        products: products,
      },
    });
  }

  var rows = Array.from(query.one(".cart-rows__box").children);
  var checkoutCart = query.one(".cart-rows__box");
  if (checkoutCart) {
    delegate(
      checkoutCart,
      "mouseover",
      ".column-action .bp3-button.bp3-minimal",
      function (e) {
        var t = e.currentTarget || e.target;
        var cartItem = query.ancestor(t, ".cart-column__product");
        var indexOfItem = rows.indexOf(cartItem);
        if (products) {
          g.lastCartProdId = get(products[indexOfItem], ["id"]);
        }
      }
    );
  }
</script>
" 

script_clickConfirmCheckout="
<script>
  var g = window.i13n;
  var get = g.get;
  var query = g.query;
  var merge = g.merge;
  var getNum = g.getNum;
  var getElValue = g.getElValue;

  var promotion;
  var shipping;
  var pricesInfo = query.one(".cart-checkout__prices");
  if (pricesInfo) {
    pricesInfo = pricesInfo.innerText;
    promotion = getNum(pricesInfo.match(/活動減免\s\-\$[\d]+/));
    shipping = getNum(pricesInfo.match(/本島運費\s\$[\d]+/));
  }
  var revenue = getNum(query.one(".price-subtotal .price-amount"));
  var bonus = getNum(query.one(".price-bonus .price-amount"));

  g.dispatch("action", {
    wait: 99,
    stop: true,
    lazyKey: "Purchase",
    I13N: {
      stepNo: 4,
      action: "ClickConfirmCheckout",
    },
    i13nCb: function (e, I13N, p, state) {
      I13N = merge(I13N, {
        products: g.getCheckoutProducts(),
        revenue: revenue,
        shipping: shipping,
        bonus: bonus,
        promotion: promotion,
      });
      return I13N;
    },
  });
</script>
" 

script_clickRemoveCart="
<script>
  var g = window.i13n;
  g.dispatch("action", {
    I13N: {
      action: "RemoveFromCart",
    },
    i13nCb: function (e, I13N, params) {
      I13N.products = [{ id: g.lastCartProdId }];
      return I13N;
    },
  });
</script>
"

script_initCheckout2="
<script>
  console.log('script_initCheckout2');
  var g = window.i13n;
  var get = g.get;
  var getNum = g.getNum;
  var merge = g.merge;
  var getRandomId = g.getRandomId;
  var products = g.getCheckoutProducts() || [];
  if (products) {
    g.dispatch({
      i13nPage: {
        stepNo: 5,
        products: products,
      },
    });
  }
  g.dispatch("action", {
    withLazy: "Purchase",
    i13nCb: function (e, I13N) {
      console.log(I13N);
      return I13N;
    },
  });
</script>
" 

; undone
script_purchase="
<script>
  console.log("script_purchase");
  var g = window.i13n;
  var getRandomId = g.getRandomId;
  var query = g.query;
  var getUrl = g.getUrl;
  var getNum = g.getNum;
  var merge = g.merge;

  g.dispatch("action", {
    withLazy: "Purchase",
    i13nCb: function (e, I13N, p, state) {
      var getShoplineOrderId = function () {
        var matchId = getUrl("orderId");
        if (matchId) {
          return matchId;
        } else {
          return getRandomId();
        }
      };
      I13N = merge(I13N, {
        action: "Purchase",
        purchaseId: getShoplineOrderId,
      });
      console.log(I13N);
      return I13N;
    },
  });
</script>
"






script_globalAddToCart="
<script>
  var g = window.i13n;
  var get = g.get;
  var query = g.query;
  var text = g.text;
  var getNum = g.getNum;
  var merge = g.merge;
  var getElValue = g.getElValue;
  g.dispatch("action", {
    i13nCb: function (e, I13N, p, state) {
      var ct = e.currentTarget || p.currentTarget;
      var ctParent = query.ancestor(ct, ".banner-product-card");
      var pImgDom = ctParent.querySelector(
        "a.banner-product-card__image-container"
      );
      var pId = pImgDom
        .getAttribute("href")
        .match(/product\/\d+/)[0]
        .slice(8);
      var pName = text(ctParent.querySelector(".banner-product-card__title"));
      var pPrice = getNum(
        ctParent.querySelector(".banner-product-card__price")
      );
      var categorys = query.all(".bp3-breadcrumbs .pet-breadcrumb__item");
      var category = text(
        categorys && categorys.length && categorys.slice(-1)[0]
      );
      pInfo = {
        id: pId,
        name: pName,
        price: pPrice,
        category: category,
      };
      I13N = {
        action: p[0],
        products: [merge(pInfo, { quantity: 1 })],
      };
      return I13N;
    },
  });
</script>
" 
 
script_addToCart="
<script>
  var g = window.i13n;
  var get = g.get;
  var merge = g.merge;
  var getElValue = g.getElValue;
  g.dispatch("action", {
    i13nCb: function (e, I13N, p, state) {
      var quantity = getElValue('.number-picker__input input[type="number"]');
      var pInfo = get(state.get("pInfo"));
      I13N = {
        action: p[0],
        products: [merge(pInfo, { quantity: quantity })],
      };
      return I13N;
    },
  });
</script>
" 

script_initDetail="
<script>
  var g = window.i13n;
  var get = g.get;
  var query = g.query;
  var text = g.text;
  var getNum = g.getNum;
  var name = g.text(g.query.one(".info__title"));
  var brand = g.text(g.query.one(".info__brand"));
  var price = g.getNum(g.query.one(".info__selling-price"));
  var id = location.pathname.slice(9);

  var pInfo = {
    id: id,
    name: name,
    price: price,
    brand: brand,
  };
  g.dispatch({
    pInfo: pInfo,
    i13nPage: {
      detailProducts: [pInfo],
    },
  });
</script>
" 

script_clickProduct="
<script>
  var g = window.i13n;
  var query = g.query;
  var text = g.text;
  var getNum = g.getNum;
  g.dispatch("action", {
    wait: 1,
    I13N: {
      action: "ClickProduct",
    },
    i13nCb: function (e, I13N) {
      var ct = e.currentTarget;
      var pId = ct
        .getAttribute("href")
        .match(/product\/\d+/)[0]
        .slice(8);
      var ctParent = query.ancestor(ct, ".banner-product-card");
      var pName = text(ctParent.querySelector(".banner-product-card__title"));
      var pPrice = getNum(
        ctParent.querySelector(".banner-product-card__price")
      );
      var pData = {
        id: pId,
        name: pName,
        price: pPrice,
      };
      I13N.products = [pData];
      return I13N;
    },
  });
</script>
" 

script_initSearch="
<script>
  var g = window.i13n;
  var getUrl = g.getUrl;
  var keyword = getUrl("search");
  if (keyword) {
    g.dispatch("action", {
      I13N: {
        action: "Search",
        label: {
          search_string: keyword,
        },
      },
    });
  }
</script>
" 

script_initCategory="
<script>
  var g = window.i13n;
  var query = g.query;
  var text = g.text;
  var getNum = g.getNum;
  var objectToArray = g.objectToArray;
  var parseJson = g.parseJson;
  var getProducts = function () {
    var arr = {};
    var products = query.all(".banner-product-card");
    var categorys = query.all(".bp3-breadcrumbs .pet-breadcrumb__item");
    var category = text(
      categorys && categorys.length && categorys.slice(-1)[0]
    );
    products.forEach(function (product, key) {
      var pName = text(product.querySelector(".banner-product-card__title"));
      var pPrice = getNum(product.querySelector(".banner-product-card__price"));
      var pId = product
        .querySelector("a.banner-product-card__image-container")
        .getAttribute("href")
        .match(/product\/\d+/)[0]
        .slice(8);
      arr[pId] = {
        name: pName,
        id: pId,
        category: category,
        position: key,
        price: pPrice,
      };
    });
    return arr;
  };
  var arrP = getProducts();
  g.dispatch({
    i13nPage: {
      impressions: objectToArray(arrP),
    },
  });
</script>
" 

script_initUserId="
<script>
var g = window.i13n;
  var get = g.get;
  var isReady = false;

  var uid = get(
    omnichatTracker.find(function(item) {
      if (Array.isArray(item)) {
        var json = JSON.stringify(item);
        return json.includes("memberId");
      }
      return false;
    }),
    [2, "memberId"]
  );
  console.log({uid});
  if (uid && uid !== "0") {
    g.dispatch({ uid: uid });
    g.uid = uid;
    isReady = true;
  }
</script>
"

script_refund="
<script>
  var g = window.i13n;
  var q = g.query;
  var text = g.text;
  var getUrl = g.getUrl;
  var refundId = getUrl("orderId");

  g.dispatch("action", {
    I13N: {
      action: "Refund",
      refundId: refundId,
    },
  });
</script>
"