; www.qiaohu.com 

; Tags
tag_usergram_enabled=true
tag_usergram_id="UgBbOP-1"
tag_usergram_test=true
tag_usergram_cv[]=CompleteRegistration
tag_usergram_cv[]=Purchase
tag_usergram_cv[]=Sample
tag_usergram_attr_birthdayYear=prop01
tag_usergram_attr_name=prop02
tag_usergram_attr_revenue=prop03
tag_usergram_attr_gift=prop04
tag_usergram_attr_state=prop05
tag_usergram_attr_giveOrSelf=prop06
tag_usergram_attr_payment=prop07

; Router


router_rules[]="/"
router_pages[]=index

router_rules[]="/Reg/GoActivePage"
router_pages[]=memberActive

router_rules[]="/*"
router_pages[]='all'


; Page
page_all_scripts[]=initUserId
page_all_params[]=[]
; page_all_secs[]='clickTest'

page_memberActive_secs[]=addMember

page_index_secs[]=applySample

; Section
sec_addMember_selects[]='form [type="submit"]'
sec_addMember_types[]=click
sec_addMember_scripts[]=addMember
sec_addMember_params[]=[]

sec_applySample_selects[]='form[action*="/site/experienceDataAdd"] input[name="submit"]'
sec_applySample_types[]=click
sec_applySample_scripts[]=applySample
sec_applySample_params[]=[]

; Script
;
script_applySample="
<script>
var g = window.i13n;
var query = g.query;
var text = g.text;
g.dispatch('action', {
  I13N: {
    action: 'Sample',
  },
  i13nCb: function(e, I13N) {
    var birthdayYear = text(query.one('#year').value); 
    console.log(e, birthdayYear);
  }
});
</script>
"

script_addMember="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    action: 'CompleteRegistration',
  }
});
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = false;
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
