; www.qiaohu.com 

; Tags
tag_usergram_enabled=true
tag_usergram_id="UgBbOP-1"
tag_usergram_test=true
tag_usergram_attr_birthdayYear=prop01
tag_usergram_attr_name=prop02
tag_usergram_attr_revenue=prop03
tag_usergram_attr_gift=prop04
tag_usergram_attr_state=prop05
tag_usergram_attr_orderType=prop06
tag_usergram_attr_payment=prop07

; Router
router_rules[]="/*"
router_pages[]='all'


; Page
page_all_scripts[]=initUserId
page_all_params[]=[]
; page_all_secs[]='clickTest'

; Section

; sec_clickLine_selects[]="#line"
; sec_clickLine_types[]="click"
; sec_clickLine_scripts[]="clickLine"
; sec_clickLine_params[]=[]

; Script

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = false;
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
