; www.qiaohu.com 

; Tags
tag_usergram_enabled=true
tag_usergram_id="UgBbOP-1"
tag_usergram_test=true
tag_usergram_cv[]=CompleteRegistration
tag_usergram_cv[]=Purchase
tag_usergram_cv[]=Sample
tag_usergram_attr_birthdayYear=prop01
tag_usergram_attr_name=prop02
tag_usergram_attr_revenue=prop03
tag_usergram_attr_gifts=prop04
tag_usergram_attr_state=prop05
tag_usergram_attr_giveOrSelf=prop06
tag_usergram_attr_payment=prop07

; Router

router_rules[]="/"
router_pages[]=index

router_rules[]="/apply*"
router_pages[]=apply

router_rules[]="/Reg/GoActivePage"
router_pages[]=memberActive

router_rules[]="/*"
router_pages[]='all'


; Page
page_all_scripts[]=initUserId
page_all_params[]=[]
page_all_secs[]=purchase

page_memberActive_secs[]=addMember

page_index_secs[]=applySample

page_apply_secs[]=applySample


; Section
sec_addMember_selects[]='form [type="submit"]'
sec_addMember_types[]=click
sec_addMember_scripts[]=addMember
sec_addMember_params[]=[]

; Sec applySample
sec_applySample_selects[]='form[action*="/site/experienceDataAdd"] input[name="submit"]'
sec_applySample_types[]=click
sec_applySample_scripts[]=applySample
sec_applySample_params[]=[]

sec_applySample_selects[]='form[action*="/site/index"] img#submitimg_button'
sec_applySample_types[]=click
sec_applySample_scripts[]=applySample
sec_applySample_params[]=[]

; Sec purchase 
sec_purchase_selects[]='form[action*="/Order/Save"] input.submit'
sec_purchase_types[]=click
sec_purchase_scripts[]=purchase
sec_purchase_params[]=[]

sec_purchase_selects[]='form[action*="/Order/Save"] button[type="submit"]'
sec_purchase_types[]=click
sec_purchase_scripts[]=purchase
sec_purchase_params[]=[]

; Script

script_purchase="
<script>
var g = window.i13n;
var getRadioValue = g.getRadioValue;
var getElValue = g.getElValue;
var query = g.query;
var text = g.text;
var getNum = g.getNum;
var lazyKey = 'Purchase';
var getLabel = function(selector, parentSelector) {
  var allRadios = query.all(selector); 
  var toLabel = function(radio) {
    var p = query.ancestor(radio, parentSelector);
    return text(p);
  };
  let label;
  allRadios.some(function(radio){
    if (radio.checked) {
      label = toLabel(radio);
      return true;
    } else {
      return false;
    }
  });
  return label;
};

var isMobile = -1 !== document.URL.indexOf('//morder');

var getPcProduct = function(prodEl) {
  var pSelector = 'div.dingg_jf_xzlw';
  var pDiv = query.ancestor(prodEl, pSelector);
  var name = text(pDiv.querySelector('p'));
  var price = text(pDiv.querySelector('p span'));
  return {
    name: name,
    price: price
  };
};

var getMobileProduct = function(prodEl) {
  var pDiv = query.ancestor(prodEl, 'div.ui-radio');
  var ppDiv = query.ancestor(pDiv, 'div');
  var name = text(ppDiv.querySelector('table tr td:first-child'));
  var price = getNum(ppDiv.querySelector('table tr td:nth-child(2) p span'));
  return {
    name: name,
    price: price
  };
};

var giftFilter = function(item) { return !!item; };

var getPcGifts = function(id) {
  var gift1 = getLabel('input[name="selectGift_'+ id +'"]', 'li');
  var gift2 = getLabel('input[name="gift_'+ id +'_1_numlist[]"]', 'span');
  var gift3 = getLabel('input[name="gift_'+ id +'_0_numlist[]"]', 'span');
  return [gift1, gift2, gift3].filter(giftFilter);
};

var getMobileLabel = function(selector) {
  var el = query.ancestor(selector, '.swipe_content');
  if (!el) {
    return false;
  }
  var label = text(el.querySelector('.red_border p'));
  return label;
};

var getMobileGifts = function(id) {
  var gifts = [];
  var gift1 = getMobileLabel('input[name="fixed_gift_'+ id+ '"]:checked');
  var gift2 = getMobileLabel('input[name="gift_'+ id+ '_1_numlist[]"]:checked');
  var gift3 = getMobileLabel('input[name="gift_'+ id+ '_0_numlist[]"]:checked');
  return [gift1, gift2, gift3].filter(giftFilter);
};

var getPcRevenue = function() {
 return getNum(query.one('#total_price span span:nth-child(3)'));
};

var getMobileRevenue = function() {
 return getNum(query.one('#select_price span:nth-child(3)'));
};

var getPcPayment = function() {
  return getLabel('input[name="payment"]', 'span'); 
};

var getMobilePayment = function() {
    var paymentEl = query.one('input[name="payment"]:checked');
    if (paymentEl) {
      var paymentId = paymentEl.id;
      return text(query.one('label[for="'+paymentId+'"]'));
    } else {
      return '';
    }
};

g.dispatch('action', {
  wait: 0,
  lazyKey: lazyKey,
  I13N: {
    action: lazyKey,
  },
  i13nCb: function(e, I13N) {
    var target = e.currentTarget;
    var form = target.form;
    var id = getRadioValue(form.querySelectorAll('input[name="length"]'));
    var prodEl = query.one('#order_period_'+id);
    var prod = (isMobile) ? getMobileProduct(prodEl) : getPcProduct(prodEl);
    var products = [
      {
        name: prod.name,
        price: prod.price,
        id: id,
        quantity: id,
      }
    ];
    I13N.products = products;
    I13N.gifts = (isMobile) ? getMobileGifts(id) : getPcGifts(id);
    I13N.state = getElValue(form.querySelector('select[name="province"]'));
    I13N.revenue = (isMobile) ? getMobileRevenue() : getPcRevenue();
    I13N.birthdayYear = getElValue('#year');
    I13N.giveOrSelf = getRadioValue(form.querySelectorAll('input[name="is_gift"]')) === '1' ? 'give' : 'self'; 
    I13N.payment = (isMobile) ? getMobilePayment() : getPcPayment(); 
    return I13N;
  }
});
</script>
"

script_applySample="
<script>
var g = window.i13n;
var text = g.text;
var getElValue = g.getElValue;
var lazyKey = 'Sample';
g.dispatch('action', {
  wait: 0,
  lazyKey: lazyKey,
  I13N: {
    action: lazyKey,
  },
  i13nCb: function(e, I13N) {
    var birthdayYear = getElValue('#year') || getElValue('#bb_year');
    var state = getElValue('#s_province');
    I13N.birthdayYear = birthdayYear;
    I13N.state = state;
    return I13N;
  }
});
</script>
"

script_addMember="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    action: 'CompleteRegistration',
  }
});
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = false;
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
