; Tags
currencyCode=TWD
tags_gtag_enabled=true
tags_gtag_id="GTM-TW79K5B"
tags_gtag_gaId="UA-124534784-1"
tags_usergram_enabled=true
tags_usergram_id="Ug2wHB-1"
tags_usergram_test=true

; Router
router_rules[]="/"
router_pages[]=home

router_rules[]="/product_category*"
router_pages[]=category

router_rules[]="/product_detail*"
router_pages[]=detail

router_rules[]="/*"
router_pages[]='all'

; Page
page_home_scripts[]=viewContent
page_home_params[]=["home"]

page_all_secs[]=footer
page_all_secs[]=menu

page_category_scripts[]=getPrice
page_category_params[]=[]
page_category_scripts[]=initCategory
page_category_params[]=[]
page_category_secs[]=filter
page_category_secs[]=productList

page_detail_scripts[]=getPrice
page_detail_params[]=[]
page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_secs[]=addToCart

; Section
sec_footer_selects[]=".footer_copyright a"
sec_footer_types[]="click"
sec_footer_scripts[]="clickFooter"
sec_footer_params[]=[]

sec_footer_selects[]='.footer_copyright a[href*="line.me"]'
sec_footer_types[]="click"
sec_footer_scripts[]="clickConcat"
sec_footer_params[]=[]

sec_menu_selects[]="li[id*=id_store_top_menu_li] a"
sec_menu_types[]="click"
sec_menu_scripts[]="clickMenu"
sec_menu_params[]=[]

sec_menu_selects[]="li[class*=store_top_menu_]"
sec_menu_types[]="click"
sec_menu_scripts[]="clickMenu"
sec_menu_params[]=[]

sec_filter_selects[]=".div_small_side_menu_list input"
sec_filter_types[]="change"
sec_filter_scripts[]="changeFilter"
sec_filter_params[]=[]

sec_filter_selects[]=".div_small_side_menu_list i[onclick*="to_set_attribute_tag"]"
sec_filter_types[]="click"
sec_filter_scripts[]="changeFilter"
sec_filter_params[]=[]

sec_productList_selects[]=".product_item a"
sec_productList_types[]="click"
sec_productList_scripts[]="clickProduct"
sec_productList_params[]=[]

sec_addToCart_selects[]=".standard_quantity_context a"
sec_addToCart_types[]="click"
sec_addToCart_scripts[]="addToCart"
sec_addToCart_params[]=[]

; Script 
script_viewContent="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    type: 'cv',
    action: 'ViewContent',
  },
  i13nCb: function(e, I13N, params) {
    I13N.label = {pageName: params[0]};
    return I13N;
  },
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
})
</script>
"

script_clickFooter="
<script>
var g = window.i13n;
g.dispatch('action', {
  stop: true,
  I13N: {
    type: 'event',
    action: 'clickFooter',
  },
  i13nCb: function(e, I13N) {
    var target = e.target;
    var a = g.query.ancestor(target, 'a');
    I13N.label = { pageName:  a.href };
    return I13N;
  }
});
</script>
"

script_clickMenu="
<script>
var g = window.i13n;
var query = g.query;
g.dispatch('action', { 
  stop: true,
  I13N: {
    type: 'event',
    action: 'clickMenu'
  },
  i13nCb: function(e, I13N) {
    var t = e.target;
    var pDiv = query.ancestor(t, '[id*="id_store_top_menu_"]');
    var pId = pDiv.id.split('_').slice(-1)[0];
    var layers = [];
    var t1 = query.one('#id_store_top_image_'+pId).innerText;
    layers.push(t1);
    var secondLayer = query.ancestor(t, '[class*="store_top_menu_2"]');
    var t2;
    if (secondLayer) {
      var secP = query.ancestor(secondLayer, 'ul');
      t2 = secP.querySelector('[class*="store_top_menu_1"]').innerText;
    }
    if (t2) {
      layers.push(t2);
    }
    layers.push(t.innerText);
    I13N.label = {layers: layers};
    return I13N;
  }
});
</script>
"
script_getPrice="
<script>
var g = window.i13n;
var numReg = /\d+/g;
g.getPrice = function(s) {
  return s.replace(',','').match(numReg)[0];
}
</script>
"

script_initCategory="
<script>
var g = window.i13n;
var query = g.query;
var getUrl = g.getUrl;
var getPrice = g.getPrice;
var getMinMax = function() {
  var min = query.one('input[name*=attribute_min_price]');
  var max = query.one('input[name*=attribute_max_price]');
  var minV = (min) ? min.value : null;
  var maxV = (max) ? max.value : null;
  return [min, max];
};
var getProductId = function(a) {
  return getUrl('product_sn', a.href);
};
var products = query.all('.product_item');
var arrP = [];
var category = query.one('.div_product_directory .list_selected');
if (category) {
  category = category.innerText;
}
products.forEach(function(product, key){
  var name = product.querySelector('.product_name').innerText;
  var id = getProductId(product.querySelector('a'));
  var price = getPrice(product.querySelector('.product_price').innerText);
  arrP[id] = {
    name: name,
    id: id,
    price: Number(price),
    category: category,
    list: 'Category',
    position: key,
  };
});

g.dispatch('config/set', {
  filterPrice: getMinMax(),
  getMinMax: getMinMax,
  getProductId: getProductId,
  arrP: arrP,
  i13nPage: {
    ecommerceImpressions: arrP.map(function(p){return p;}),
  }
});
</script>
"

script_initDetail="
<script>
var g = window.i13n;
var getPrice = g.getPrice;
var query = g.query;
var getUrl = g.getUrl;
var pName = query.one('.product_name').innerText;
var categorys = query.all('.product_category_path a');
var arrC = categorys.map(function(c){
  return c.innerText;
});
var pInfo = {
  name: pName,
  id: getUrl('product_sn'),
  price: getPrice(query.one('.sale_price_value').innerText),
  category: JSON.stringify(arrC)
};
var ecommerce = {
  detail: {
    actionField: {list: 'detail'},
    products: [pInfo]
  }
};
g.dispatch('config/set', {
  detailInfo: pInfo,
  i13nPage: {
    ecommerceDetail: ecommerce
  }
});
</script>
"

script_addToCart="
<script>
  var g = window.i13n;
  var query = g.query;
  var qtySel = query.one('.standard_quantity_context select');
  var radios = query.all('.table_standard_attribute input');
  var variant;
  radios.some(function(radio){
    if (radio.checked) {
      var p = query.ancestor(radio, 'td');
      variant = p.getAttribute('title');
      return true;
    } else {
      return false;
    }
  });
  g.dispatch('action', { 
    I13N: {
      type: 'cv',
      action: 'AddToCart',
      category: 'Ecommerce',
    },
    i13nCb: function(e, I13N, p, state) {
      const pInfo = state.get('detailInfo').toJS();
      pInfo.quantity = qtySel.value;
      pInfo.variant = variant;
      I13N.ecommerceAddToCart = [pInfo];
      return I13N;
    }
  });
</script>
"

script_clickProduct="
<script>
var g = window.i13n;
g.dispatch('action', { 
  stop: true,
  I13N: {
    type: 'event',
    action: 'clickProduct',
    category: 'Ecommerce',
  },
  i13nCb: function(e, I13N, p, state) {
    var t = e.currentTarget;
    var getId = state.get('getProductId');  
    var id = getId(t);
    var products = state.get('arrP').toJS();
    I13N.ecommerce={
      click: {
        actionField: {
          list: 'Category'
        },
        products: [products[id]] 
      },
    };
    return I13N;
  },
});
</script>
"

script_changeFilter="
<script>
var g = window.i13n;
var query = g.query;
g.dispatch('action', { 
  stop: true,
  I13N: {
    type: 'event',
    action: 'changeFilter'
  },
  i13nCb: function(e, I13N, p, state) {
    if ('click' === e.type) {
      var newPrice = state.get('getMinMax')();
      var price = state.get('filterPrice');
      if (newPrice[0] === price[0] && newPrice[1] === price[1]) {
        return false;
      }
    }
    var arrLi = query.all('.div_small_side_menu_list li');
    var arrSec = query.all('.div_small_side_menu_list .menu_level_3_outside');
    var arrSel = [];
    arrLi.forEach(function(li, liKey){
      var title = li.innerText;
      var inputs = Array.from(arrSec[liKey].querySelectorAll("input"));
      inputs.forEach(function(input){
        if (input.checked) {
          var dLabel = query.ancestor(input, 'label').innerText;
          arrSel.push([title, dLabel]);
        } else if ('text' === input.type) {
          arrSel.push([title, input.value, input.getAttribute('placeholder')]);
        }
      })
    });
    I13N.label = arrSel;
    return I13N;
  }
})
</script>
"
