; Tags
currencyCode=TWD
tags_gtag_enabled=true
tags_gtag_id="GTM-TW79K5B"
tags_gtag_gaId="UA-124534784-1"

tags_usergram_enabled=false
tags_usergram_id=""
tags_usergram_test=true
tags_usergram_attrs_Product=prop01

tags_debug_enabled=true

; Router
router_rules[]="/"
router_pages[]=home

router_rules[]="/product/goods_detail*"
router_pages[]=detail

router_rules[]="/*"
router_pages[]='all'

; Page
page_home_scripts[]=viewContent
page_home_params[]=["home"]
page_all_secs[]=hpAd

page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_scripts[]=setPageCategory
page_detail_params[]=["detail"]
page_detail_secs[]=addToCart

page_all_secs[]=footer
page_all_secs[]=menu

; Section
sec_menu_selects[]=".nav a"
sec_menu_types[]="click"
sec_menu_scripts[]="clickMenu"
sec_menu_params[]=[]

sec_hpAd_selects[]=".ad #tab_nav a"
sec_hpAd_types[]="mouseover"
sec_hpAd_scripts[]="hpAdHover"
sec_hpAd_params[]=[]

sec_hpAd_selects[]=".ad #tab_nav a"
sec_hpAd_types[]="click"
sec_hpAd_scripts[]="hpAdClick"
sec_hpAd_params[]=[]

sec_addToCart_selects[]="a.buy[id*='shop']"
sec_addToCart_types[]="click"
sec_addToCart_scripts[]="addToCart"
sec_addToCart_params[]=[]

sec_footer_selects[]=".footer a"
sec_footer_types[]="click"
sec_footer_scripts[]="clickFooter"
sec_footer_params[]=[]

; Script 
script_viewContent="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    type: 'cv',
    action: 'ViewContent',
  },
  i13nCb: function(e, I13N, params) {
    I13N.label = {pageName: params[0]};
    return I13N;
  },
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
})
</script>
"

script_initDetail="
<script>
var g = window.i13n;
var query = g.query;
var getUrl = g.getUrl;
var name = query.one(".main-title").innerText;
var id = getUrl('goods_id');
var pInfo = {
  name: name,
  id: id
};
g.dispatch('config/set', {
  detailInfo: pInfo,
  i13nPage: {
    detailProducts: [pInfo]
  }
});
</script>
"

script_setPageCategory="
<script>
var g = window.i13n;
g.dispatch('action', {
  stop: true,
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
});
</script>
"

script_clickMenu="
<script>
  var g = window.i13n;
  var query = g.query;
  g.dispatch('action', {
    stop: true,
    I13N: {
      type: 'event',
      action: 'clickMenu'
    },
    i13nCb: function(e, I13N) {
      var t = e.target;
      var layers = [];
      var p = query.ancestor(t, 'li');
      if (p) {
        var t1 = query.one('h5');
        layers.push(t1.innerText);
      }
      layers.push(t.innerText);
      I13N.label = {layers: layers};
      return I13N;
    }
  });
</script>
"

script_clickFooter="
<script>
console.log('click footer');
</script>
"

script_hpAdHover="
<script>
  var g = window.i13n;
  var query = g.query;
  var getSelected = function () {
    var adSelected;
    var ads = query.all('.ad #panes div');
    ads.some(function(ad, key){
      if ('block' === ad.style.display) {
        adSelected = key;
        return true;
      } else {
        return false;
      }
    });
    return adSelected;
  };
  var getTabIndex = function(el) {
    var hoverIndex;
    var tabs = query.all('.ad #tab_nav a');
    tabs.some(function(tab, key){
      if (tab.isSameNode(el)) {
       hoverIndex = key;
       return true;
      } else {
        return false;
      }
    });
    return hoverIndex;
  };
  g.dispatch('config/set', { 
    getSelected: getSelected,
    getTabIndex: getTabIndex,
    adSelected: getSelected()
  });
  g.dispatch('action', { 
    I13N: {
      type: 'event',
      action: 'adHover',
    },
    i13nCb: function(e, I13N, p, state) {
      var t = e.currentTarget;
      I13N.label = {
        selected: getSelected(),
        hover: getTabIndex(t),
      };
      return I13N;
    }
  });
</script>
"

script_hpAdClick="
<script>
  var g = window.i13n;
  g.dispatch('action', { 
    I13N: {
      type: 'event',
      action: 'unnecessaryClick',
    },
    i13nCb: function(e, I13N, p, state) {
      var t = e.currentTarget;
      var selected = state.get('adSelected');
      var getTabIndex = state.get('getTabIndex');
      var tabIndex = getTabIndex(t);
      if (selected === tabIndex) {
        I13N.label = {
          selected: selected,
          click: tabIndex
        };
        return I13N;
      } else {
        return null;
      }
    }
  });
</script>
"

script_addToCart="
<script>
  var g = window.i13n;
  var query = g.query;
  var getNum = g.getNum;
  g.dispatch('action', { 
    stop: true,
    I13N: {
      type: 'cv',
      action: 'AddToCart',
      category: 'Ecommerce',
    },
    i13nCb: function(e, I13N, p, state) {
      const pInfo = state.get('detailInfo').toJS();
      var t = e.currentTarget;
      var p = query.ancestor(t, 'tr');
      var priceNode = p.querySelector('td:nth-child(2)');
      var price = getNum(priceNode.innerText);
      var variantNeode = p.querySelector('td:nth-child(1)');
      var variant = variantNeode.innerText;

      pInfo.variant = variant;
      pInfo.price = price;
      I13N.ecommerceAddToCart = [pInfo];
      return I13N;
    }
  });
</script>
"

