; Tags
currencyCode=TWD
tags_gtag_enabled=true
tags_gtag_id="GTM-TW79K5B"
tags_gtag_gaId="UA-124534784-1"
tags_usergram_enabled=false
tags_usergram_id="Ug2wHB-1"
tags_usergram_test=true
tags_debug_enabled=true

; Router
router_rules[]="/"
router_pages[]=home

router_rules[]="/product/goods_detail*"
router_pages[]=detail

router_rules[]="/*"
router_pages[]='all'

; Page
page_home_scripts[]=viewContent
page_home_params[]=["home"]

page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_scripts[]=setPageCategory
page_detail_params[]=["detail"]
page_detail_secs[]=addToCart

page_all_secs[]=footer
page_all_secs[]=menu

; Section
sec_menu_selects[]=".nav a"
sec_menu_types[]="click"
sec_menu_scripts[]="clickMenu"
sec_menu_params[]=[]

sec_addToCart_selects[]="a.buy[id*='shop']"
sec_addToCart_types[]="click"
sec_addToCart_scripts[]="addToCart"
sec_addToCart_params[]=[]

sec_footer_selects[]=".footer a"
sec_footer_types[]="click"
sec_footer_scripts[]="clickFooter"
sec_footer_params[]=[]

; Script 
script_viewContent="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    type: 'cv',
    action: 'ViewContent',
  },
  i13nCb: function(e, I13N, params) {
    I13N.label = {pageName: params[0]};
    return I13N;
  },
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
})
</script>
"

script_initDetail="

"

script_setPageCategory="
<script>
var g = window.i13n;
g.dispatch('action', {
  stop: true,
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
});
</script>
"

script_clickMenu="
<script>
  var g = window.i13n;
  var query = g.query;
  g.dispatch('action', {
    stop: true,
    I13N: {
      type: 'event',
      action: 'clickMenu'
    },
    i13nCb: function(e, I13N) {
      var t = e.target;
      var layers = [];
      var p = query.ancestor(t, 'li');
      if (p) {
        var t1 = query.one('h5');
        layers.push(t1.innerText);
      }
      layers.push(t.innerText);
      I13N.label = {layers: layers};
      return I13N;
    }
  });
</script>
"

script_clickFooter="
<script>
console.log('click footer');
</script>
"

script_addToCart="
<script>
  var g = window.i13n;
  var query = g.query;
  var getNum = g.getNum;
  g.dispatch('action', { 
    stop: true,
    I13N: {
      type: 'cv',
      action: 'AddToCart',
      category: 'Ecommerce',
    },
    i13nCb: function(e, I13N, p, state) {
      var t = e.currentTarget;
      var p = query.ancestor(t, 'tr');
      var priceNode = p.querySelector('td:nth-child(2)');
      var price = getNum(priceNode.innerText);
      var product = {
        price: price
      };
      I13N.ecommerceAddToCart = [product];
      return I13N;
    }
  });
</script>
"

