; Tags
currencyCode=TWD

tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_gaId="UA-127045625-2"
tag_gtag_bCookieIndex=1

tag_usergram_enabled=true
tag_usergram_id="UgW1ov-1"
tag_usergram_test=true
tag_usergram_cv[]=CompleteRegistration
tag_usergram_cv[]=Purchase
tag_usergram_attr_birthdayYear=prop01
tag_usergram_attr_city=prop02
tag_usergram_attr_job=prop03
tag_usergram_attr_sex=prop04
tag_usergram_attr_matrimony=prop05
tag_usergram_attr_name=prop06
tag_usergram_attr_quantity=prop07
tag_usergram_attr_revenue=prop08
tag_usergram_attr_promote=prop09

; Router
router_rules[]="/"
router_pages[]=home

router_rules[]="/product/goods_detail*"
router_pages[]=detail

router_rules[]="/shopping/shopping"
router_pages[]=shoppingCart

router_rules[]="/shopping/shopping3"
router_pages[]=fillMemberInfo

router_rules[]="/shopping/shopping4"
router_pages[]=b4Purchase

router_rules[]="/*"
router_pages[]='all'

; Page
page_home_scripts[]=viewContent
page_home_params[]=["home"]

page_detail_scripts[]=initDetail
page_detail_params[]=[]
page_detail_scripts[]=setPageCategory
page_detail_params[]=["detail"]
page_detail_secs[]=addToCart

page_shoppingCart_secs[]=clickCheckout

page_fillMemberInfo_scripts[]=initFillMemberInfo
page_fillMemberInfo_params[]=[]
page_fillMemberInfo_secs[]=addMember

page_b4Purchase_scripts[]=purchase
page_b4Purchase_params[]=[]
page_b4Purchase_secs[]=clickPurchase

page_all_scripts[]=initUserId
page_all_params[]=[]
page_all_secs[]=hpAd
page_all_secs[]=footer
page_all_secs[]=menu

; Section
sec_menu_selects[]=".nav a"
sec_menu_types[]="click"
sec_menu_scripts[]="clickMenu"
sec_menu_params[]=[]

sec_hpAd_selects[]=".ad #tab_nav a"
sec_hpAd_types[]="mouseover"
sec_hpAd_scripts[]="hpAdHover"
sec_hpAd_params[]=[]

sec_hpAd_selects[]=".ad #tab_nav a"
sec_hpAd_types[]="click"
sec_hpAd_scripts[]="hpAdClick"
sec_hpAd_params[]=[]

sec_addToCart_selects[]="a.buy[id*='shop']"
sec_addToCart_types[]="click"
sec_addToCart_scripts[]="addToCart"
sec_addToCart_params[]=[]

sec_footer_selects[]=".footer a"
sec_footer_types[]="click"
sec_footer_scripts[]="clickFooter"
sec_footer_params[]=[]

sec_clickCheckout_selects[]="[onclick*=startSubmit]"
sec_clickCheckout_types[]="click"
sec_clickCheckout_scripts[]="clickCheckout"
sec_clickCheckout_params[]=[]

sec_addMember_selects[]=".total a.btn2"
sec_addMember_types[]="click"
sec_addMember_scripts[]="addMember"
sec_addMember_params[]=[]

sec_clickPurchase_selects[]="#btnSend"
sec_clickPurchase_types[]="click"
sec_clickPurchase_scripts[]="clickPurchase"
sec_clickPurchase_params[]=[]

; Script 
script_viewContent="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    action: 'ViewContent',
  },
  i13nCb: function(e, I13N, params) {
    I13N.label = {pageName: params[0]};
    return I13N;
  },
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
})
</script>
"

script_initDetail="
<script>
var g = window.i13n;
var query = g.query;
var getUrl = g.getUrl;
var name = query.one(".main-title").innerText;
var id = getUrl('goods_id');
var pInfo = {
  name: name,
  id: id
};
g.dispatch('config/set', {
  detailInfo: pInfo,
  i13nPage: {
    detailProducts: [pInfo]
  }
});
</script>
"

script_setPageCategory="
<script>
var g = window.i13n;
g.dispatch('action', {
  i13nPageCb: function(action, I13N, params){
    return {p: params[0]};
  }
});
</script>
"

script_clickMenu="
<script>
  var g = window.i13n;
  var query = g.query;
  g.dispatch('action', {
    wait: 0,
    I13N: {
      action: 'clickMenu'
    },
    i13nCb: function(e, I13N) {
      var t = e.target;
      var layers = [];
      var p = query.ancestor(t, 'li');
      if (p) {
        var t1 = query.one('h5');
        layers.push(t1.innerText);
      }
      layers.push(t.innerText);
      I13N.label = {layers: layers};
      return I13N;
    }
  });
</script>
"

script_clickFooter="
<script>
</script>
"

script_hpAdHover="
<script>
  var g = window.i13n;
  var query = g.query;
  var getSelected = function () {
    var adSelected;
    var ads = query.all('.ad #panes div');
    ads.some(function(ad, key){
      if ('block' === ad.style.display) {
        adSelected = key;
        return true;
      } else {
        return false;
      }
    });
    return adSelected;
  };
  var getTabIndex = function(el) {
    var hoverIndex;
    var tabs = query.all('.ad #tab_nav a');
    tabs.some(function(tab, key){
      if (tab.isSameNode(el)) {
       hoverIndex = key;
       return true;
      } else {
        return false;
      }
    });
    return hoverIndex;
  };
  g.dispatch('config/set', { 
    getSelected: getSelected,
    getTabIndex: getTabIndex,
    adSelected: getSelected()
  });
</script>
"

script_hpAdClick="
<script>
  var g = window.i13n;
  g.dispatch('action', { 
    I13N: {
      action: 'unnecessaryClick',
    },
    i13nCb: function(e, I13N, p, state) {
      var t = e.currentTarget;
      var selected = state.get('adSelected');
      var getTabIndex = state.get('getTabIndex');
      var tabIndex = getTabIndex(t);
      if (selected === tabIndex) {
        I13N.label = {
          selected: selected,
          click: tabIndex
        };
        return I13N;
      } else {
        return null;
      }
    }
  });
</script>
"

script_addToCart="
<script>
  var g = window.i13n;
  var query = g.query;
  var getNum = g.getNum;
  g.dispatch('action', { 
    wait: 0,
    I13N: {
      action: 'AddToCart',
      category: 'Ecommerce',
    },
    i13nCb: function(e, I13N, p, state) {
      const pInfo = state.get('detailInfo').toJS();
      var t = e.currentTarget;
      var p = query.ancestor(t, 'tr');
      var priceNode = p.querySelector('td:nth-child(2)');
      var price = getNum(priceNode.innerText);
      var variantNeode = p.querySelector('td:nth-child(1)');
      var variant = variantNeode.innerText;

      pInfo.variant = variant;
      pInfo.price = price;
      I13N.ecommerceAddToCart = [pInfo];
      return I13N;
    }
  });
</script>
"

script_clickCheckout="
<script>
var g = window.i13n;
g.dispatch('action', {
  wait: 0,
  I13N: {
    action: 'ClickCheckout',
    stepNo: 1,
  }
});
</script>
"

script_initFillMemberInfo="
<script>
var g = window.i13n;
g.dispatch('action', {
  I13N: {
    action: 'FillMemberInfo',
    stepNo: 2,
  }
});
</script>
"

script_addMember="
<script>
var g = window.i13n;
var q = g.query;
var getOptionText = g.getOptionText;
var birthdayYear = q.one('select[name=regYear]').value;
var dCitySel = q.one('select[name=city2]');
var city = getOptionText(dCitySel);
var gender = q.one('input[name=sex1]:checked').value;
g.dispatch('action', {
  wait: 0,
  I13N: {
    action: 'CompleteRegistration',
    label: { 
      birthdayYear: birthdayYear,
      city: city,
      regType: 'site member',
      gender: (('M'===gender) ? 'male' : 'female'),
    }
  }
});
</script>
"

script_purchase="
<script>
var g = window.i13n;
var q = g.query;
var getNum = g.getNum;
var getUrl = g.getUrl;
var text = g.text;
var queryFrom = g.queryFrom;

var getProdId = function(el) {
  var id = null;
  var dLink = el.querySelector('a[href*="goods_id"]');
  if (dLink) {
    id = getUrl('goods_id', dLink.href);
  }
  return id;
};

var getProdItem = function(tr) {
  var tds = queryFrom(tr).all('td');
  var promoteIndex = (tds.length > 5) ? 5 : 4;
  var name = text(tds[0]);
  var price = getNum(tds[1]);
  var id = getProdId(tr); 
  var quantity = getNum(tds[2]);
  var promote = text(tds[promoteIndex]); 
  return {
    name: name,
    promote: promote,
    price: price,
    id: id,
    quantity: quantity
  };
};

var getProducts = function() {
  var arrTr = q.all('.carlist tbody tr');
  var products = arrTr.map(function(tr){
    return getProdItem(tr); 
  });
  return products;
};

var city = '';
var revenue = 0;
var dCity = q.all('.order'); 
if (dCity && dCity.length) {
  dCity = dCity[1].querySelector('table tr:nth-child(3) td');
  city = dCity.innerText.split(/\s/)[1];
}
var dRevenue = q.one('.steptotal2 .money .red');
if (dRevenue) {
  revenue = getNum(dRevenue.innerText);
}

g.dispatch('action', {
  wait: 99,
  stop: true,
  lazyKey: 'Purchase',
  withLazy: 'Purchase',
  I13N: {
    purchaseId: (new Date()).getTime(),
    action: 'Purchase',
    city: city,
    revenue: revenue,
    products: getProducts(),
  }
});
</script>
"

script_clickPurchase="
<script>
var g = window.i13n;
g.dispatch('action', {
  wait: 0,
  lazyKey: 'Purchase',
  withLazy: 'Purchase'
});
</script>
"

script_initUserId="
<script>
var g = window.i13n;
var getCookie = g.getCookie;
var u = getCookie('STE_SECURE_COOKIE_KEY');
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
