; User: Test 

; Tags
currencyCode=TWD
tagId=OA-c1af6551
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp

; Router
router_rules[]="/*"
router_pages[]='allInit'

; Page
page_allInit_scripts[]=testScript
page_allInit_params[]=[]
page_allInit_secs[]=testClick

; Section
sec_testClick_selects[]="#test-link"
sec_testClick_types[]="click"
sec_testClick_scripts[]="testClick"
sec_testClick_params[]=[]

; Script
script_testScript="
<script>
console.log('test');
</script>
"

script_testClick="
<script>
var g = window.i13n;
g.dispatch('action', { 
  I13N: {
    action: 'ClickTest',
  },
  i13nCb: function(e, I13N, p, state) {
    console.log('Click Test');
    return I13N;
  },
});
</script>
"
