; Test 
; Tags
currencyCode=TWD
tagId=test
tag_gtag_enabled=true
tag_gtag_id="GTM-TW79K5B"
tag_gtag_bCookieIndex=1
tag_gtag_lazeInfoIndex=2
tag_gtag_downstreams[]=mp

; Router
router_rules[]="/*"
router_pages[]='allInit'

; Page
page_allInit_scripts[]=testScript
page_allInit_params[]=[]

; Script
script_refund="
<script>
console.log('test');
</script>
"
