; Bebit

; Tags
tag_usergram_enabled=true
tag_usergram_id="UgVTMw-1"
tag_usergram_test=false
tag_usergram_cv[]=Schedule
tag_usergram_attr_gender=prop01
tag_usergram_attr_city=prop03
tag_usergram_attr_category=prop04
tag_usergram_attr_department=prop05

; Router
router_rules[]="/*"
router_pages[]='all'
router_rules[]="/contact/*"
router_pages[]='contact'


; Page
page_contact_secs[]="contact"


; Section
sec_contact_selects[]="form button[type=submit]"
sec_contact_types[]="delegate"
sec_contact_scripts[]="submitContact"
sec_contact_params[]=[]


; Script
script_submitContact="
<script>
var g = window.i13n;
var get = g.get;

g.dispatch('action', {
  I13N: {
    action: 'Schedule'
  },
  i13nCb: function(e, I13N, params) {
    var fm = get(e, ['currentTarget', 'form']); 
    var els = get(fm, ['elements'], {});
    var city = get(els, ['your-place', 'value']);
    var category = get(els, ['your-content', 'value']);
    var department = get(els, ['your-department', 'value']);
    I13N.label = {
      city: city,
      category: category,
      department: department
    };
    return I13N;
  }
});
</script>
"


script_initUserId="
<script>
var g = window.i13n;
var get = g.get;
var u = get(window, ['serviceId']);
if (u) {
  g.dispatch({ uid: u });
}
</script>
"
